/**
 * Generators for the three human-readable documents DevCortex writes into
 * `.cortex/` at init time: the project brief, the architecture map, and the
 * quality constitution.
 *
 * Each generator is a pure function of the detected stack + cached graph (+
 * config), so output is deterministic and round-trippable in tests. The MCP
 * `get_project_brief` / `get_architecture_map` / `get_quality_constitution`
 * tools read these files back verbatim, so the content is real, derived from the
 * actual scan — never a placeholder.
 */
import type {
  CortexConfig,
  DetectedStack,
  OperatingMode,
  ProjectGraph,
  RiskLevel,
} from '../domain/index';

/** Rendered for any section whose underlying list is empty. */
const NONE = '_none_';

/** Render a markdown bullet list, falling back to a stable empty marker. */
function bullets(items: string[]): string {
  if (items.length === 0) {
    return NONE;
  }
  return items.map((item) => `- ${item}`).join('\n');
}

/** Shared stack summary used by the brief, the map, and the constitution. */
function stackLines(stack: DetectedStack): string {
  const version = stack.frameworkVersion !== undefined ? ` ${stack.frameworkVersion}` : '';
  const targets =
    stack.deploymentTargets.length > 0 ? stack.deploymentTargets.join(', ') : NONE;
  return [
    `- **Framework:** ${stack.framework}${version}`,
    `- **Language:** ${stack.language}`,
    `- **Package manager:** ${stack.packageManager}`,
    `- **Monorepo:** ${stack.monorepo ? 'yes' : 'no'}`,
    `- **Deployment targets:** ${targets}`,
  ].join('\n');
}

/**
 * `.cortex/project.md` — a concise brief: stack, operating posture, headline
 * stats, the route table, and the package scripts. Surfaced by
 * `cortex.get_project_brief`.
 */
export function renderProjectBrief(graph: ProjectGraph, config: CortexConfig): string {
  const { stack, stats } = graph;

  const routes = [...graph.routes]
    .sort((a, b) => a.routePath.localeCompare(b.routePath))
    .map((route) => `- \`${route.routePath}\` -> ${route.file} (${route.kind})`);

  const scripts = Object.entries(graph.scripts)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, command]) => `- \`${name}\`: ${command}`);

  return `${[
    '# Project Brief',
    '',
    `> Generated by DevCortex at ${graph.generatedAt}. Regenerate with \`devcortex scan\`.`,
    '',
    '## Stack',
    stackLines(stack),
    '',
    '## Operating posture',
    `- **Mode:** ${config.mode}`,
    `- **Privacy:** ${config.privacy}`,
    '',
    '## At a glance',
    `- **Files:** ${stats.fileCount}`,
    `- **Routes:** ${stats.routeCount} (API: ${stats.apiCount})`,
    `- **Tests:** ${stats.testCount}`,
    `- **Risky surfaces:** ${stats.riskyCount}`,
    '',
    '## Routes',
    bullets(routes),
    '',
    '## Scripts',
    bullets(scripts),
  ].join('\n')}\n`;
}

/**
 * `.cortex/architecture.md` — the structural map: stack, file-kind breakdown,
 * API endpoints, risky surfaces, environment variables, and dependency hotspots
 * (the most depended-upon files, where blast radius is widest). Surfaced by
 * `cortex.get_architecture_map`.
 */
export function renderArchitectureMap(graph: ProjectGraph): string {
  const { stack } = graph;

  const kindCounts = new Map<string, number>();
  for (const file of graph.files) {
    kindCounts.set(file.kind, (kindCounts.get(file.kind) ?? 0) + 1);
  }
  const kinds = [...kindCounts.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([kind, count]) => `${kind}: ${count}`);

  const apiEndpoints = [...graph.routes]
    .filter((route) => route.kind === 'api')
    .sort((a, b) => a.routePath.localeCompare(b.routePath))
    .map((route) => `\`${route.routePath}\` -> ${route.file}`);

  const riskyFiles = [...graph.riskyFiles].sort((a, b) => a.localeCompare(b));

  const envVars = [...graph.envVars]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      (env) =>
        `\`${env.name}\`${env.documented ? '' : ' (undocumented)'} — used in ${env.usedIn.length} file(s)`,
    );

  const hotspots = [...graph.files]
    .filter((file) => file.importedBy.length > 0)
    .sort(
      (a, b) => b.importedBy.length - a.importedBy.length || a.path.localeCompare(b.path),
    )
    .slice(0, 10)
    .map((file) => `${file.path} — imported by ${file.importedBy.length} file(s)`);

  return `${[
    '# Architecture Map',
    '',
    `> Generated by DevCortex at ${graph.generatedAt}. Regenerate with \`devcortex scan\`.`,
    '',
    '## Stack',
    stackLines(stack),
    '',
    '## File kinds',
    bullets(kinds),
    '',
    '## API endpoints',
    bullets(apiEndpoints),
    '',
    '## Risky surfaces',
    '> Auth, billing, middleware, migration, env and config files — edits here are risk-floored.',
    bullets(riskyFiles),
    '',
    '## Environment variables',
    bullets(envVars),
    '',
    '## Dependency hotspots',
    '> The most depended-upon files — changes here have the widest blast radius.',
    bullets(hotspots),
  ].join('\n')}\n`;
}

/** Plain-language meaning of each operating mode (exhaustive over OperatingMode). */
const MODE_MEANINGS: Record<OperatingMode, string> = {
  passive: 'observes and advises, never blocks',
  guarded: 'blocks high/critical-risk work until evidence is supplied',
  autopilot: 'blocks only critical-risk work',
};

/** One markdown checkbox line per gate. */
function gateLine(label: string, enabled: boolean): string {
  return `- [${enabled ? 'x' : ' '}] **${label}** — ${enabled ? 'required' : 'disabled'}`;
}

/**
 * `.cortex/quality-constitution.md` — the contract the gates enforce, derived
 * from the config: operating posture, required gates, gate commands, risk
 * floors, protected paths, forced stack packs, and the detected stack. Surfaced
 * by `cortex.get_quality_constitution`.
 */
export function renderQualityConstitution(config: CortexConfig, stack: DetectedStack): string {
  const commands = Object.entries(config.commands)
    .filter((entry): entry is [string, string] => typeof entry[1] === 'string')
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([gate, command]) => `\`${gate}\`: \`${command}\``);

  const floors = Object.entries(config.risk.floors)
    .filter((entry): entry is [string, RiskLevel] => entry[1] !== undefined)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([taskType, level]) => `**${taskType}** -> minimum risk \`${level}\``);

  const protectedPaths = [...config.risk.protectedPaths]
    .sort((a, b) => a.localeCompare(b))
    .map((pattern) => `\`${pattern}\``);

  const stackPacks = config.stackPacks.map((id) => `\`${id}\``);

  return `${[
    '# Quality Constitution',
    '',
    '> Generated by DevCortex from `.cortex/config.yaml`. This is the contract the gates enforce.',
    '',
    '## Operating posture',
    `- **Mode:** ${config.mode} (${MODE_MEANINGS[config.mode]})`,
    `- **Privacy:** ${config.privacy}`,
    `- **Block unproven done:** ${
      config.gates.blockUnprovenDone
        ? 'yes — a "done" claim is rejected without supporting evidence'
        : 'no'
    }`,
    '',
    '## Required gates',
    gateLine('Type-check', config.gates.typecheck),
    gateLine('Lint', config.gates.lint),
    gateLine('Build', config.gates.build),
    gateLine('Test', config.gates.test),
    '',
    '## Gate commands',
    bullets(commands),
    '',
    '## Risk floors',
    '> Task types pinned to a minimum risk level regardless of other signals.',
    bullets(floors),
    '',
    '## Protected paths',
    '> Edits matching these globs are treated as high/critical risk.',
    bullets(protectedPaths),
    '',
    '## Forced stack packs',
    bullets(stackPacks),
    '',
    '## Stack',
    `Detected stack: **${stack.framework} (${stack.language}, ${stack.packageManager})**. ` +
      'Stack-specific best practices, anti-patterns and version checks are supplied by the ' +
      'matching stack pack(s).',
  ].join('\n')}\n`;
}
